/**
 * The design tokens as CSS custom properties.
 *
 * React Native reads the tokens directly; a browser cannot, so this turns the same objects
 * into `--gr-*` variables. `bun run design:sync` writes the result to
 * `apps/web/src/styles/tokens.css`, which Tailwind's `@theme` block then maps to utility
 * classes — so `bg-surface` in the studio and `theme(name).surface` in the app are the same
 * value by construction rather than by discipline.
 *
 * Generated rather than hand-maintained for the same reason the font stack is: two
 * hand-kept copies of a palette diverge, and the divergence shows up as a screenshot in the
 * studio that doesn't match the phone.
 *
 * String building only — no I/O. `packages/core` stays platform-pure; the script that writes
 * the file lives at the repo root.
 */
import { COVER_COLOURWAYS } from "./cover.ts";
import { THEME_NAMES, type ThemeName, type ThemeTokens, theme } from "./themes.ts";
import { MOTION, RADIUS, SPACING, TYPE_SCALE, type TypeToken } from "./tokens.ts";

/** `--gr-ink`, `--gr-mark-saffron`, … for one theme. */
export function themeCssVariables(name: ThemeName): Record<string, string> {
	const tokens: ThemeTokens = theme(name);
	return {
		"--gr-background": tokens.background,
		"--gr-surface": tokens.surface,
		"--gr-surface-sunken": tokens.surfaceSunken,
		"--gr-paper": tokens.paper,
		"--gr-ink": tokens.ink,
		"--gr-ink-muted": tokens.inkMuted,
		"--gr-ink-faint": tokens.inkFaint,
		"--gr-rule": tokens.rule,
		"--gr-accent": tokens.accent,
		"--gr-accent-ink": tokens.accentInk,
		"--gr-accent-muted": tokens.accentMuted,
		"--gr-mark-saffron": tokens.marks.saffron,
		"--gr-mark-leaf": tokens.marks.leaf,
		"--gr-mark-sky": tokens.marks.sky,
		"--gr-mark-rose": tokens.marks.rose,
		"--gr-overlay": tokens.overlay,
		"--gr-grain-opacity": String(tokens.grain.opacity),
		"--gr-grain-blend": tokens.grain.blend,
		"--gr-color-scheme": tokens.isDark ? "dark" : "light",
	};
}

/** The theme-independent half: spacing, radii, motion and the type scale. */
export function metricCssVariables(): Record<string, string> {
	const variables: Record<string, string> = {};

	for (const [token, value] of Object.entries(SPACING)) {
		variables[`--gr-space-${token}`] = `${value}px`;
	}
	for (const [token, value] of Object.entries(RADIUS)) {
		variables[`--gr-radius-${token}`] = `${value}px`;
	}
	variables["--gr-duration-tap"] = `${MOTION.tap}ms`;
	variables["--gr-duration-transition"] = `${MOTION.transition}ms`;
	variables["--gr-duration-sheet"] = `${MOTION.sheet}ms`;
	variables["--gr-easing"] = `cubic-bezier(${MOTION.easing.join(", ")})`;

	// Latin metrics only. A Gujarati size is derived per script by `resolveTypeStyle`, and
	// baking one into a variable would be exactly the shortcut the type scale exists to
	// prevent — `ScriptureText` on the web calls core like the app does.
	for (const [token, spec] of Object.entries(TYPE_SCALE)) {
		const name = kebab(token as TypeToken);
		variables[`--gr-text-${name}`] = `${spec.size}px`;
		variables[`--gr-leading-${name}`] = String(spec.lineHeight);
	}

	return variables;
}

function kebab(token: TypeToken): string {
	return token.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function block(selector: string, variables: Record<string, string>): string {
	const body = Object.entries(variables)
		.map(([name, value]) => `\t${name}: ${value};`)
		.join("\n");
	return `${selector} {\n${body}\n}`;
}

/**
 * The whole stylesheet.
 *
 * White is the default on `:root`; the other three are selected by `data-theme` on the
 * document element, and a dark system preference upgrades the default to Dark unless a
 * `data-theme` has been set explicitly. Sepia and Black are never reachable from a media
 * query — they are choices a reader makes, and the OS cannot express them.
 */
export function designTokensCss(): string {
	const parts: string[] = [
		"/**",
		" * Generated by `bun run design:sync` from packages/core/src/design/ — do not edit.",
		" *",
		" * The design language's tokens as CSS variables. Tailwind maps them to utilities in",
		" * src/styles.css; anything outside Tailwind can use `var(--gr-ink)` directly.",
		" */",
		"",
		block(":root", { ...metricCssVariables(), ...themeCssVariables("white") }),
		"",
		block(':root[data-theme="white"]', themeCssVariables("white")),
	];

	for (const name of THEME_NAMES.filter((candidate) => candidate !== "white")) {
		parts.push("", block(`:root[data-theme="${name}"]`, themeCssVariables(name)));
	}

	parts.push(
		"",
		"@media (prefers-color-scheme: dark) {",
		block(":root:not([data-theme])", themeCssVariables("dark"))
			.split("\n")
			.map((line) => `\t${line}`)
			.join("\n"),
		"}",
		"",
		"/* Cover colourways, so a static page can render a shelf without JavaScript. */",
		block(
			":root",
			Object.fromEntries(
				COVER_COLOURWAYS.flatMap((colourway) => [
					[`--gr-cover-${colourway.id}`, colourway.base],
					[`--gr-cover-${colourway.id}-ink`, colourway.ink],
				]),
			),
		),
		"",
	);

	return parts.join("\n");
}
