import { Image, StyleSheet, View } from "react-native";

import { useTheme } from "@/theme/theme-provider";

/**
 * The paper grain: a 128px tile of monochrome noise, laid over a surface at 4–7%.
 *
 * It is the only texture in the product. Flat digital fills band on OLED panels and read as
 * a web view rather than as a page; a hint of grain fixes both, and is the difference
 * between "a screen with a warm background colour" and "paper".
 *
 * Mid-grey noise does both jobs with one asset: over light paper it darkens into fibre, over
 * a dark ground it lightens into film grain. The tile is generated by `bun run design:sync`
 * and committed, so it cannot drift between builds.
 *
 * Rendered as a sibling overlay rather than a background because React Native has no
 * `background-image`: the tile is an `Image` with `resizeMode="repeat"`, absolutely filling
 * its parent and transparent to touches.
 */
export function PaperGrain({ radius }: { radius?: number }) {
	const { grain } = useTheme();

	// Black theme sets the opacity to zero: grain on a true black OLED panel is noise on
	// pixels that would otherwise be off.
	if (grain.opacity === 0) {
		return null;
	}

	return (
		<View
			style={[
				StyleSheet.absoluteFill,
				styles.clip,
				radius === undefined ? null : { borderRadius: radius },
			]}
		>
			<Image
				source={require("@/assets/textures/paper-grain.png")}
				resizeMode="repeat"
				style={[styles.tile, { opacity: grain.opacity }]}
			/>
		</View>
	);
}

const styles = StyleSheet.create({
	clip: {
		overflow: "hidden",
		pointerEvents: "none",
	},
	tile: {
		width: "100%",
		height: "100%",
	},
});
